### ISSUE TITLE
installation nit picks   + divide by 0

### ISSUE THREAD

**Issue by chrismrutherford** [v2rockets/Loyal-Elephie#1]
Thanks for releasing this. A couple of install issues. 'cookie' and 'jsonwebtoken' missing from npm packages. Readme missing cd to frontend before npm i. Backend instructions missing -r from install requirement. 

npm install @types/cookie -D
npm install @types/jsonwebtoken -D

Also getting this error:

Traceback (most recent call last):

File "/mnt/ai/repos/Loyal-Elephie/backend/app.py", line 13, in <module>

update_thread = UpdateThread(server_state)

File "/mnt/ai/repos/Loyal-Elephie/backend/file_monitor.py", line 41, in __init__

update_corpus() # probably better start in memory server

File "/mnt/ai/repos/Loyal-Elephie/backend/bm25_api.py", line 53, in update_corpus

bm25 = BM25Okapi(processed_corpus, k1=1.5, b=0.75, epsilon=0.25)

File "/home/chris/miniconda3/envs/elephine/lib/python3.10/site-packages/rank_bm25.py", line 83, in __init__

super().__init__(corpus, tokenizer)

File "/home/chris/miniconda3/envs/elephine/lib/python3.10/site-packages/rank_bm25.py", line 27, in __init__

nd = self._initialize(corpus)

File "/home/chris/miniconda3/envs/elephine/lib/python3.10/site-packages/rank_bm25.py", line 52, in _initialize

self.avgdl = num_doc / self.corpus_size

ZeroDivisionError: division by zero

I commented out bm25 = BM25Okapi(processed_corpus, k1=1.5, b=0.75, epsilon=0.25) to get the chat session started. it works! but im probably running a broken instance without BM25Okapi

**Comment by v2rockets** [comment]
Thank you for raising the issue! I did forgot to update several files, and now it should be fixed with commit [d3601fb3ba317ac49e4abceb2829678fbf8332ed](https://github.com/v2rockets/Loyal-Elephie/commit/d3601fb3ba317ac49e4abceb2829678fbf8332ed). Please retry with npm -i and let me know if it works by now!
